### ISSUE TITLE
Update to MM v1.6

### ISSUE THREAD

**Issue by Chocohead** [modmuss50/OptiFabric#1]
I've exposed the classpath addition in [`ClassTinkerer`](https://github.com/Chocohead/Fabric-ASM/blob/v1.6/src/com/chocohead/mm/api/ClassTinkerers.java#L58-L70) now so the whole `me.modmuss50.optifabric.mod.asm` package can be removed. The static block in [`MixinPlugin`](https://github.com/modmuss50/OptiFabric/blob/master/src/main/java/me/modmuss50/optifabric/mod/asm/MixinPlugin.java#L17-L27) would need to stay of course, but having a plugin just to load early could be avoided with an early riser. You'd need something like [this](https://github.com/Chocohead/Fabric-ASM/blob/v1.6/example/resources/fabric.mod.json#L21-L25) in the fabric.mod.json and the actual implementation is just a `Runnable` like [this](https://github.com/Chocohead/Fabric-ASM/blob/v1.6/example/src/com/chocohead/mm/testing/EarlyRiser.java). It would load Optifine fractionally later compared to plugin construction, but it's still long before any Minecraft code has been defined let alone loaded.

Think this would also free up licensing to be what you wanted too rather than having my MPL v2 code somewhat limiting your options (unless you've managed to copy some more I've just missed of course).

**Comment by modmuss50** [comment]
Looks good, the code that is there is a bit of a mess, before I thought I could get away with just copying a bit of your stuff, but ended up using it as a lib (hence the license).

I did see the early riser stuff, that should be perfect for what I need.

Thanks for taking a look at this.

**Comment by Chocohead** [comment]
[`c4ad22d`](https://jitpack.io/com/github/Chocohead/Fabric-ASM/c4ad22d/build.log) works properly on Jitpack as a replacement for `v1.6` until the next release tag.

**Comment by modmuss50** [comment]
Should all be sorted now, thanks
