### ISSUE TITLE
Fabric Rendering API is not compatible with the shaders mod vertex format.

### ISSUE THREAD

**Issue by Slye-Fox** [modmuss50/OptiFabric#10]
When I try to use Optifabric(0.2.0) with Optifine(1.14.2_HD_U_F1_pre6), this is what I get:
https://www.dropbox.com/s/rv7ojtz6rxu0sq6/Optifine.png?dl=0
I have Fabric API(0.3.0+build.175) & Fabric Loader(0.4.8+build.154).

(Sorry about the dropbox link, I was having trouble uploading it to here & imgur)

**Comment by modmuss50** [comment]
Known issue, disable shaders for now.

I will update this post once it’s fixed.

**Comment by Slye-Fox** [comment]
Ah, okay then.
Thank you for the quick response.

**Comment by OS-Void** [comment]
I get the same issue without shaders

**Comment by haodadajipai** [comment]
> 没有着色器，我得到同样的问题
😱
impossible

**Comment by modmuss50** [comment]
Yeah, this only occurs if you use the shader pipeline in optifine. Make sure you are not using the internal option as well.

**Comment by Dinolek** [comment]
You can disable always-tesselate-blocks in config to fix this for now.

**Comment by KingReboot2** [comment]
So will this be fixed so we can use shaders in the future

**Comment by Slye-Fox** [comment]
> 
> 
> So will this be fixed so we can use shaders in the future

You can use shaders now, you just have to disable 'always-tesselate-blocks' in the optifabric config file.

**Comment by KingReboot2** [comment]
oh

**Comment by KingReboot2** [comment]
where is that located?

**Comment by neico** [comment]
Slightly related, albeit not as serious: https://github.com/FabricMC/fabric/issues/221#issuecomment-496545791

Seems like those options aren't as stable as they seem to be...

**Comment by ghost** [comment]
Downgrading to Fabric API 0.3.0-pre build 157a lets you use shaders. I have no issues running this with the latest optifine and optifabric. This is on 1.14.2 by the way.

**Comment by Romaq** [comment]
For me, 1.14.2 OptiFabric does not display the ground. My default is "no Shaders". Optifabric-0.2.0.jar, preview_OptiFine_1.14.2_HD_U_F1_pre6.jar, fabric-api-0.3.0+build.175.jar. 4G memory, and this is true with only Vanilla as the resource pack.

The preview of Optifine works showing the ground, and if I rename OptiFabric*.jar~ and *Optifine*.jar~ (turning them off) Fabric displays fine. I do have screenshots I can upload if necessary. I understand "bugs are expected with a preview Optifine", that's cool. :) I can pick Fabric when I need my map and Optifine if I need things to look pretty. ;-)

**Comment by ghost** [comment]
@romaq are you using canvas render by chance? That caused me to not have any blocks display if I loaded the game with canvas, optifine, and optifabric. 

If you don't want to use shaders the most recent fabric API will be fine as long as they are off. 

The blocks not rendering is more than likely something conflicting with either optifine or optifabric

**Comment by Romaq** [comment]
I'm not clear what "canvas rendering" is. VoxelMap *might* be doing something with rendering, but I would not know the details. I can turn it off and report tomorrow. The only other mod is the AutoFisher, which should have no impact on rendering. I'll look tomorrow for clarification on what to test and report.

**Comment by ghost** [comment]
https://minecraft.curseforge.com/projects/canvas-renderer is what I was talking about. It's the only thing that gave me issue. I have the latest of voxel and autofish as well and neither cause problems.

**Comment by Romaq** [comment]
I'm not using the Canvas mod. I'll try switching off VoxelMap tomorrow,play
with driver updates, and so on. Thank you. Knowing you are using the same
mods with success helps.

**Comment by Cynosphere** [comment]
For those not using shaders and still not seeing the world properly, disable Render Regions.

**Comment by Romaq** [comment]
That's it! I turned it off, the ground is back now. I'm not clear if that is a bug that should be fed up the chain to Optifine or not, but if @Cynosphere or someone else knows the specifics of how Optifine "ought" to work combined with Fabric when Render Regions is enabled, or any other details behind this, I would be grateful. Since turning it off fixes my specific problem, and I have no clue in hell what is going on behind the scenes, I don't feel adequate to report a "bug," or even which part of the eco-system to report his as a bug "to." But if someone else can get a handle on this in my place, it would be happy to have this problem go away for the next person. :)

**Comment by modmuss50** [comment]
This issue will not be fixed, sorry about that.

More info: https://github.com/modmuss50/OptiFabric/blob/master/README.md
