### ISSUE TITLE
[Not game-braking] Fancy grass broken

### ISSUE THREAD

**Issue by Evska1** [modmuss50/OptiFabric#102]
![2019-11-24_08 40 11](https://user-images.githubusercontent.com/58109391/69492183-d171c980-0e96-11ea-9151-1d2e21afd60d.png)
The fancy grass feature in optifine works occasionally
Im using OptiFine 1.14.4 HD U F4 i tested OptiFine 1.14.4 HD U F2 and the same happend not sure about F1 and F3

**Comment by enveeed** [comment]
In what way is it broken? Isn't it supposed to only use top top texture for the sides of the block when the lower one next to it is also grass / snowy?

**Comment by Evska1** [comment]
> In what way is it broken? Isn't it supposed to only use top top texture for the sides of the block when the lower one next to it is also grass / snowy?

Wait yep your right how awkward

**Comment by enveeed** [comment]
Could you close this issue in that case?

**Comment by Evska1** [comment]
> Could you close this issue in that case?

How I'm new to this! Sorry for the inconvenience
