### ISSUE TITLE
[0.7.1] Brakes higher-end shaderpacks with current version

### ISSUE THREAD

**Issue by TrueDevron** [modmuss50/OptiFabric#109]
![broke](https://user-images.githubusercontent.com/57275365/71117207-992b8580-21cd-11ea-9ab2-ab9e1c1d9588.png)

Causes these weird 'dots' to appear wherever and whenever I move. Didn't appear on 0.7.0.
0.7.1 also caused me to crash when joining servers, but after updated fabric api / loader it stopped.

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
