### ISSUE TITLE
Crash when loading

### ISSUE THREAD

**Issue by stw222** [modmuss50/OptiFabric#11]
im not sure if im doing something wrong or not but it seems to crash for me on 1.14.2.
I have optifabric and preview_OptiFine_1.14.2_HD_U_F1_pre6.jar in my MultiMC mods folder

crash log:
[https://paste.ee/p/8GC4I](https://paste.ee/p/8GC4I)

MultiMC console log:
[https://paste.ee/p/A39Xb](https://paste.ee/p/A39Xb)

**Comment by stw222** [comment]
even on a clean instance of MC, it still crashes when i only have fabric loader, API, optifabric, and optifine pre6.

it didnt generate a crash log but this is the multimc console:
[https://paste.ee/p/t15qS](https://paste.ee/p/t15qS)

**Comment by modmuss50** [comment]
**java.util.zip.ZipError: zip END header not found**

Does the game still run without Optifabric? I dont think this an optifabric issue.

**Comment by stw222** [comment]
it works fine with me only using vanilla + that version of optifine using this multimc tutorial for when you only want to use optifine. you just replace the version and file names accordingly.

[https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine)

**Comment by stw222** [comment]
i just tried that tutorial on my multimc instance and it didnt work. its still either optifine, or fabric with a crash when using optifabric

**Comment by calloatti** [comment]
![image](https://user-images.githubusercontent.com/12817862/58701496-76dd3200-8379-11e9-8bcd-e35c4ade4410.png)

So, it works and it does not work at the same time...

1. Create a 1.14.2 MC/Fabric instance following this tutorial step by step: https://fabricmc.net/wiki/tutorial:install_with_multimc

2. Then drop the optifine and optifabric jars in the mods folder. 

3. Shaders don't work. Everyone knows that already.

If you still have a problem, go here: https://discord.gg/v6v4pMv

**Comment by modmuss50** [comment]
Nothing I can do to fix this, it seems to be an issue with your internet.

**Comment by stw222** [comment]
when i use optifine as the only mod (no fabric) it works fine. when i use fabric with like 20 mods, it works fine. but then when i use optifabric, it crashes, even when its only fabric loader, fabric api, optifabric, and the newest optifine jar (i tried just dropping it in .minecraft/mods/ and extracting it and then placing the extracted file in there)

**Comment by stw222** [comment]
the same thing also occurs with the vanilla launcher. all i had installed is fabric loader 0.4.8 build 154- 1.14.2 build 2, fabric api 0.3.0 build 175, optifabric 0.2.0, optifine 1.14.2 pre6, and modmenu 1.5.4-85 when testing this

**Comment by stw222** [comment]
vanilla launcher console (no crash log was generated): [https://pastebin.com/50aNCSyv](https://pastebin.com/50aNCSyv)

**Comment by calloatti** [comment]
This issue was solved here:

https://discordapp.com/channels/507304429255393322/507982463449169932/584083477071134720

corrupted optifabric jar file

**Comment by AdamZGamer** [comment]
im having the same problem!
btw calloatti the link u sent doesnt go anywhere!

**Comment by AdamZGamer** [comment]
and yes i tried everything and it failed
