### ISSUE TITLE
Game crashes during startup

### ISSUE THREAD

**Issue by falloutchick** [modmuss50/OptiFabric#111]
[crash-2020-01-06_00.36.10-client.txt](https://github.com/modmuss50/OptiFabric/files/4024964/crash-2020-01-06_00.36.10-client.txt)

The game loads fine if I move both Optifine and OptiFabric out of the mod folder (since optifabric only exists to make optifine run). Optifine is doing what it's meant to by giving me shader options etc on the menus, but when I go to load the game I can see the world for half a second, then the game crashes to the launcher and I get the above crash report. A little help would be awesome, I'm trying to set this up for a hosted server.

**Comment by shadowc** [comment]
I have exactly the same issue. It seems this doesn't work for 1.14.4 :(

**Comment by Chrysheart** [comment]
This is an error that was thought to be fixed apparently, but wasn't. I also can't use it because of it crashing.

**Comment by SHsuperCM** [comment]
Same here

**Comment by shadowc** [comment]
So I downloaded a different (earlier) version of optifabric and it worked for me. I'm now in 1.15.1 so optifine is gone for a while :/

**Comment by Sparkist-ds** [comment]
It's even weirder for me. I can run the newest version of optifabric and replaymod without any problem at all (except with a bug in replaymod), but when i use an earlier version of fabric api, what you just described happens.
So far, the best setup i could get to get optifine working with fabric was:
Fabric 1.14.4 0.6.2
Fabric API 0.3.3 Build 234
Optifabric 0.5.2
Optifine 1.14.4 F4

**Comment by josephrooks** [comment]
This is the latest combo that I got working, around December 17th:

Fabric 1.14.4 0.7.2
Fabric API 0.4.2 Build 246
Optifabric 0.7.1
Optifine 1.14.4 F4

This is working for me with no issues as far as I can tell.
