### ISSUE TITLE
1.15 Please

### ISSUE THREAD

**Issue by RoboMico** [modmuss50/OptiFabric#116]
The 1.14 version is becoming obsolete and 1.15 is more popular, so please support the 1.15 version!

**Comment by HeartyYF** [comment]
Since there isn't OptiFine for 1.15, OptiFabric can't support 1.15.

**Comment by ahkui** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/OptiFine?src=hash&amp;ref_src=twsrc%5Etfw">#OptiFine</a> 1.15.1 is now 85% complete. (fixing 48 compile errors)<a href="https://twitter.com/hashtag/HashtagYouCanBlockIfYouWereOneOfRoughly439PeopleOnThatOnePollWhoOnlyWantedMajorUpdates?src=hash&amp;ref_src=twsrc%5Etfw">#HashtagYouCanBlockIfYouWereOneOfRoughly439PeopleOnThatOnePollWhoOnlyWantedMajorUpdates</a></p>&mdash; OptiFine (@OptiFineNews) <a href="https://twitter.com/OptiFineNews/status/1225154546869161985?ref_src=twsrc%5Etfw">February 5, 2020</a></blockquote>

**Comment by ahkui** [comment]
i think 1.15 will be release in next month

**Comment by modmuss50** [comment]
I cannot even start to look into it untill there is a 1.15 optifine.

**Comment by lakejason0** [comment]
But now there's one. Reopen it?

**Comment by Nixuge** [comment]
It's already done no need to reopen it
