### ISSUE TITLE
Crashes?

### ISSUE THREAD

**Issue by Toffelz** [modmuss50/OptiFabric#118]
Aparently Optifabric needs some other mods? I dont see any linked and im asuming this is a problem
![image](https://user-images.githubusercontent.com/60294130/74478208-2a0c9d80-4ead-11ea-962f-ff2240925d50.png)

![image](https://user-images.githubusercontent.com/60294130/74478223-37298c80-4ead-11ea-8b84-ac5b65398815.png)

**Comment by modmuss50** [comment]
Update fabric loder.
