### ISSUE TITLE
Chrases on Open.

### ISSUE THREAD

**Issue by Toffelz** [modmuss50/OptiFabric#119]
Game crashes whenever i open it, After i updated Fabric mod loader It crashes whenever i put Optifabric in there
![image](https://user-images.githubusercontent.com/60294130/74479563-ab652f80-4eaf-11ea-9be4-ffa7aad19ad6.png)
heres my mods

**Comment by modmuss50** [comment]
Update to beta 2 please, beta 1 had a crash with litematica
