### ISSUE TITLE
Doesn’t work with 1.14.2 Fabric MMC (yes I put it in the mods folder, didn’t work

### ISSUE THREAD

**Issue by FantasticMenace** [modmuss50/OptiFabric#12]
I’m using MMC and Fabric on 1.14.2. There’s a version out for 1.14.2, but I don’t exactly know how to download it for MMC.

**Comment by FantasticMenace** [comment]
Note: It’s a pre version right now

**Comment by modmuss50** [comment]
read the readme...

install this mod and optifine in the mods folder.

**Comment by FantasticMenace** [comment]
you really think I didn’t try that

**Comment by calloatti** [comment]
1. Create a 1.14.2 MC/Fabric instance following this tutorial step by step: https://fabricmc.net/wiki/tutorial:install_with_multimc

2. Then drop the optifine and optifabric jars in the mods folder. 

3. Shaders don't work. Everyone knows that already.

If it still doesnt work, Go here: https://discord.gg/v6v4pMv

**Comment by FantasticMenace** [comment]
I actually got a Shader to work.
![image](https://user-images.githubusercontent.com/51210896/58701960-c8bca100-83e7-11e9-8d35-51eae99fa150.png)

**Comment by FantasticMenace** [comment]
![image](https://user-images.githubusercontent.com/51210896/58702563-6ebcdb00-83e9-11e9-8e46-d4b5ddadae94.png)
