### ISSUE TITLE
Game crashes on startup with Roughly Enough Items

### ISSUE THREAD

**Issue by Firion88** [modmuss50/OptiFabric#120]
game fails to launch with optifabric and Roughly enough items.
Using optifabric beta 2 and REI 3.4.2 

[crash-2020-02-13_21.39.25-client.txt](https://github.com/modmuss50/OptiFabric/files/4201461/crash-2020-02-13_21.39.25-client.txt)

**Comment by modmuss50** [comment]
Update to beta2, this crash has been fixed.

**Comment by pabli24** [comment]
For me it still crashes on beta2

**Comment by Firion88** [comment]
im already using beta2 and still having the crash

**Comment by modmuss50** [comment]
Ah, you crash log is the wrong one.

**Comment by Firion88** [comment]
oh damn yeah it is sorry. for some it didnt generate a crash log and only the log.gz file.
the error message is:
[22:27:48] [main/INFO]: [OptiFine] *** Reflector Vanilla ***
[22:27:49] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_309::method_1466(JIIII)V has incompatible changes at opcode 308 in callback net/minecraft/class_309::onKeyAfter.
Expected: [Lnet/minecraft/class_4069;, [Z]
   Found: [Z]

**Comment by modmuss50** [comment]
Ive been looking into this, and its not an easy fix. Optifine is messing with the LVT in this method, causing this mixin to fail: <https://github.com/shedaniel/Cloth/blob/events/src/main/java/me/shedaniel/cloth/mixin/MixinKeyboard.java#L68>

I cannot undo optifines change here easily as it will break its logic.

**Comment by modmuss50** [comment]
I think I have a way to fix it, however its far from trivial

**Comment by Firion88** [comment]
hmm okay fair dues thanks for looking into it. is it more an optifine issue or REI?

**Comment by modmuss50** [comment]
Ok, I think I have it working, I have linked a test build bellow, please test that it works as expected, along with keyboard input, most notablly changing keybinds (the effected code was realted to that)

[optifabric-1.0.0-beta3-test1.jar](https://ss.modmuss50.me/optifabric-1.0.0-beta3-test1.jar)

**Comment by Firion88** [comment]
You are a legend sir, everything seems to be working fine

**Comment by modmuss50** [comment]
Thanks a lot for testing, I will push beta 3 out shortly.

**Comment by pabli24** [comment]
Yep everything working good with REI 3.4.2 and LightOverlay-4.2
