### ISSUE TITLE
Game crashes with LightOverlay mod

### ISSUE THREAD

**Issue by pabli24** [modmuss50/OptiFabric#121]
Game crashes with LightOverlay-4.2 mod and optifabric-1.0.0-beta2

**Comment by modmuss50** [comment]
please post a crash log

**Comment by pabli24** [comment]
Critical injection failure: LVT in net/minecraft/class_309::method_1466(JIIII)V has incompatible changes at opcode 289 in callback net/minecraft/class_309::onKeyAfter.
Expected: [Lnet/minecraft/class_4069;, [Z]
   Found: [Z]

**Comment by pabli24** [comment]
I downloaded LightOverlay-4.1 version and its seems working fine

**Comment by modmuss50** [comment]
That seems like a duplicate of #120
