### ISSUE TITLE
Colorful wrong display

### ISSUE THREAD

**Issue by MlgmXyysd** [modmuss50/OptiFabric#125]
![photo_2020-02-14_16-57-54](https://user-images.githubusercontent.com/17919858/74516352-35160b00-4f4b-11ea-8bb6-fa75f47797b4.jpg)
![photo_2020-02-14_16-58-04](https://user-images.githubusercontent.com/17919858/74516360-36dfce80-4f4b-11ea-94e6-2b478e822c1b.jpg)

All of a sudden, these strange things appear when I dig stone, and they will follow my cursor and disappear when I enter the world again

No crash, default config

Btw, Wurst X-Ray not work after optifabric and optifine installed

Mods List:
Optifine
OptiFabric
Wurst
fabric-api
VoxelMap

**Comment by MlgmXyysd** [comment]
Again
![photo_2020-02-14_17-05-29](https://user-images.githubusercontent.com/17919858/74516999-5d523980-4f4c-11ea-9cec-f5ba8b179a8c.jpg)
![QQ截图20200214170608](https://user-images.githubusercontent.com/17919858/74517003-5e836680-4f4c-11ea-9617-e04e41d568e0.png)
![QQ截图20200214170614](https://user-images.githubusercontent.com/17919858/74517005-5fb49380-4f4c-11ea-86e8-11b9888110b8.png)
![QQ截图20200214170624](https://user-images.githubusercontent.com/17919858/74517008-604d2a00-4f4c-11ea-96e4-5618868fc40b.png)

**Comment by Nixuge** [comment]
It's an optifine bug, wait for an official release if you want to have no issue

**Comment by modmuss50** [comment]
Closing, as apparenly its an optifine bug.
