### ISSUE TITLE
Dynamic Lighting doesn't work with Tweakeroo

### ISSUE THREAD

**Issue by Southpaw1496** [modmuss50/OptiFabric#129]
I'm running Fabric 1.15.2, tweakeroo-fabric-1.15.2-0.10.0-dev.20200121.202418, preview_OptiFine_1.15.2_HD_U_G1_pre1 and optifabric-1.0.0-beta3 on macOS Catalina 10.15.3

**Comment by pointydev** [comment]
Even though I'm running on Windows, this seems to have been fixed in this config:
```
tweakeroo-fabric-1.15.2-0.10.0-dev.20200302.214816.jar
preview_OptiFine_1.15.2_HD_U_G1_pre9.jar
optifabric-1.0.0-beta4.jar
```
