### ISSUE TITLE
Game crashes when taking a screenshot with ScreenshotToClipboard Mod

### ISSUE THREAD

**Issue by elhertz** [modmuss50/OptiFabric#131]
[ScreenshotToClipboard Mod](https://www.curseforge.com/minecraft/mc-mods/screenshot-to-clipboard-fabric)
Log: https://hastebin.com/ekowoqiqat.md
(ScreenshotToClipboard works fine without optifabric-optifine)

**Comment by amnotbananaama** [comment]
This is a duplicate of my previously closed issue, I wasn't sure if I should open a new issue or wait for mine to be re-opened. https://github.com/modmuss50/OptiFabric/issues/112

**Comment by modmuss50** [comment]
I fixed screenshots, I assume it was the same bug
