### ISSUE TITLE
Crash on version 1.15.2 with Opti G1 pre2

### ISSUE THREAD

**Issue by SnrSterling** [modmuss50/OptiFabric#132]
Pastebin crashlog: https://paste.ee/p/rC6ws
i dont know how fix it. Help please.

**Comment by justastranger** [comment]
My game is also crashing, but with a different crash.

https://paste.ee/p/wEoYQ

**Comment by modmuss50** [comment]
Seems to be due to Tweakeroo, try updating or removing it. Duplicate of #126

**Comment by SnrSterling** [comment]
Without mod Tweakeroo, too, the same crash. And without All mods, same only OptiFabric + FabricAPI + Optifine = crash

**Comment by SnrSterling** [comment]
> Without mod Tweakeroo, too, the same crash. And without All mods, same only OptiFabric + FabricAPI + Optifine = crash

Okay, the problem was in conflicts mods: REI and Tweakeroo
