### ISSUE TITLE
[1.15.2] Tech Reborn cells and fluids are invisible

### ISSUE THREAD

**Issue by justastranger** [modmuss50/OptiFabric#135]
They seem to be the only thing affected.

![2020-02-17_09 29 51](https://user-images.githubusercontent.com/6827479/74666928-088b0a80-5168-11ea-9ecf-95b3713ee9df.png)

![2020-02-17_09 29 54](https://user-images.githubusercontent.com/6827479/74666937-0de85500-5168-11ea-801c-ffd5f002b299.png)

**Comment by modmuss50** [comment]
Yes, the indigo renderer is currenly disabled.
