### ISSUE TITLE
"Saved screenshot as ..." text does not appear when taking a screenshot with F2 (1.15.2)

### ISSUE THREAD

**Issue by ilepow34** [modmuss50/OptiFabric#140]
The screenshot text does not appear when taking a screenshot by pressing F2 when running OptiFabric. It works as normal running OptiFine standalone, or Fabric with every other mod I have installed, so I'm fairly confident it's an issue with OptiFabric.

The issue occurs with the following installed:
- Minecraft 1.15.2
- Fabric loader 0.7.8 build 184
- Fabric API 0.4.32 build 292
- OptiFabric 1.0.0 beta 4
- OptiFine 1.15.2 G1 pre6

**Comment by modmuss50** [comment]
Is there anything in the log?

**Comment by ilepow34** [comment]
[latest.log](https://github.com/modmuss50/OptiFabric/files/4270875/latest.log)
It looks like it's getting a NoSuchMethodError when I try to take a screenshot. This log is from me joining a singleplayer world, pressing F2 twice, then exiting and quitting the game.

**Comment by modmuss50** [comment]
Yet another instance of where optifine is removing a method.
