### ISSUE TITLE
Crash while joining world.

### ISSUE THREAD

**Issue by NovaCoreSwe** [modmuss50/OptiFabric#141]
Fabric loader working fine with VoxelMap. When i add OptiFabric and the latest Optifine verision into the mods folder, all gets started up and i make it to the main menu. When trying to enter a world, i get the message "Saving world..." and then im back in the launcher with a crash raport, wich is attatched here.
[crash-2020-02-21_17.14.24-client.txt](https://github.com/modmuss50/OptiFabric/files/4236966/crash-2020-02-21_17.14.24-client.txt)

**Comment by modmuss50** [comment]
update optifabric
