### ISSUE TITLE
New snapshot yields error with most recent beta version of optifabric.

### ISSUE THREAD

**Issue by Bjohnson131** [modmuss50/OptiFabric#147]
When I'm using optifabric with the new snapshot (20W11A), I'm getting an error
[2020-02-23-1.log.gz](https://github.com/modmuss50/OptiFabric/files/4340769/2020-02-23-1.log.gz)

**Comment by Bjohnson131** [comment]
the above log is an error, here is the actual log:
[newlog.txt](https://github.com/modmuss50/OptiFabric/files/4340777/newlog.txt)

**Comment by modmuss50** [comment]
optifabric is only compatible with the mc versions that optifine supports. Snapshots are not supported.

**Comment by Bjohnson131** [comment]
optifine does support the version that I am on: 
![chrome_ZetAU9jxSZ](https://user-images.githubusercontent.com/1939015/77202306-0cd67a80-6abc-11ea-82fc-bc697c81bc1d.png)
