### ISSUE TITLE
Optifabric could not find Optifine jar in the mods folder

### ISSUE THREAD

**Issue by K1llersaur** [modmuss50/OptiFabric#148]
From what I saw on the github it looks like this might be the same problem as in this post about 1.14
[Here](https://github.com/modmuss50/OptiFabric/issues/99)
Tried to rename the file, extract the file, and remove some mods that were dupes or for forge not fabric, with no avail.
Happy to provide more info as needed
![image](https://user-images.githubusercontent.com/57930856/76902791-5cba0500-6862-11ea-984e-ccc157f8aae8.png)

Edit: tried with pre9 and pre15, both do the same

**Comment by modmuss50** [comment]
just put the optifine jar in the mods folder. no need to extract or do anything special

**Comment by K1llersaur** [comment]
I did the extraction was only what I tried to get it to work. because putting the Jar in does nothing it still thinks it's missing
