### ISSUE TITLE
Crashes on Launch (1.14.4)

### ISSUE THREAD

**Issue by farsdewibs0n** [modmuss50/OptiFabric#150]
Can't run optifabric on launch (0.7.1)
![gambar](https://user-images.githubusercontent.com/13050356/77577595-a9a87600-6f09-11ea-808a-e504063fffa4.png)

But able to run minecraft, but still asks for Optifine even though it is installed. (0.2.0)
![gambar](https://user-images.githubusercontent.com/13050356/77577523-8b427a80-6f09-11ea-8754-7606458f3c82.png)

**Comment by modmuss50** [comment]
put optifine in the mods folder.

**Comment by farsdewibs0n** [comment]
I did. I'm not sure why this is closed?
