### ISSUE TITLE
Hand & Items fail to render in first person with shaders | OptiFine 1.15.2 HD U G1 pre10

### ISSUE THREAD

**Issue by Alternus** [modmuss50/OptiFabric#152]
![2020-03-27_20 06 17](https://user-images.githubusercontent.com/43512466/77740014-a4ad0900-7066-11ea-957b-60fd4fd478ac.png)

**Fabric Version** 0.7.8+build. 187

**Optifabric Version** 1.0.0-beta 4 & 5
**Optifine Version** 1.15.2 HD U G1 pre10

**Launcher** MultiMC

**Tested Shaders** BSL, Chocapic, Kuda, MollyVXE & Sildurs

Issue is not apparent with a plain optifine install, only occuring with optifabric.

**Comment by modmuss50** [comment]
Should be fixed in beta 6, let me know if there are any more issues.
