### ISSUE TITLE
1.15.2 Optifabric (beta 8 i think) doesn't say what optifine download to use

### ISSUE THREAD

**Issue by buckted** [modmuss50/OptiFabric#158]
basically the title, when i load the game it just says wrong optifine download, and it needs 1.15.2 optifine, which doesn't exist.

**Comment by Xyphenore** [comment]
Optfine is available but only in preview version. The latest preview version: https://optifine.net/adloadx?f=preview_OptiFine_1.15.2_HD_U_G1_pre10.jar

**Comment by modmuss50** [comment]
pre10 is known to work.
