### ISSUE TITLE
Suggestion: change environment to client

### ISSUE THREAD

**Issue by calloatti** [modmuss50/OptiFabric#16]
It would be convenient if you could change

`"environment":"*"` to `"environment":"client"` in `fabric.mod.json`

That way, the server won't crash and burn when idiots like me place the jar in the mods folder.

I already changed it in the file I have and it does not crash now.

**Comment by modmuss50** [comment]
Good idea, I’ll get around to this soon

**Comment by modmuss50** [comment]
Done, thanks for the PR
