### ISSUE TITLE
crashing optifabric

### ISSUE THREAD

**Issue by KlientW** [modmuss50/OptiFabric#160]
my optifabric is crashin i cant lauch my laucher. https://pastebin.com/EGWTe22d

**Comment by modmuss50** [comment]
I need the whole crash log please.

**Comment by edje123** [comment]
I am also having this issue, here is my entire crash log: https://pastebin.com/bMbScykA

**Comment by oguh43** [comment]
Me 2, will post a log tomorrow

**Comment by modmuss50** [comment]
@edje123 you are using the 1.14 version of optifabric, please update the mod.

**Comment by ShayBox** [comment]
Using the latest optifabric (8) and optifine (pre12) this https://paste.nomsy.net/raw/ohodotilow
pre10 and 11 are no longer available or able to be distributed

EDIT: Even in a dev env with matching versions from this repo.

**Comment by oguh43** [comment]
Resolved
