### ISSUE TITLE
New Optifabric crashes entire game

### ISSUE THREAD

**Issue by IPlayMinecraftAlot** [modmuss50/OptiFabric#164]
i use 1.15.2 optifabric but when i try to load it it crashes my entire game. i use the most recent version of optifabric and optifine.

**Comment by IPlayMinecraftAlot** [comment]
here is my crash report
https://pastebin.com/xDN9MvV3

**Comment by modmuss50** [comment]
What version of optifine are you using?

**Comment by bottobotty** [comment]
i had same issue with optifine pre13

**Comment by IPlayMinecraftAlot** [comment]
i was using pre13 like Bottobotty

**Comment by juliavdkris** [comment]
Yep, same issue here. Latest version of everything, haven't tried other versions yet.
Fabric 0.7.10 build.191-1.15.2
Fabric API 0.5.1 build.294-1.15
Optifabric 0.7.1
Optifine 1.15.2 pre13

https://pastebin.com/prb4c8Qs

EDIT: I am an idiot. Latest version of optifabric from curseforge only supports up to pre4. Latest GitHub release works fine!

**Comment by mucitrus** [comment]
@samvdkris Where did you find the lastest GITHUB version? Looks like it is the same as Curseforge have. Did you still use Pre13 optifine?

I have also the same issue download latest everything crashing the launcher KAPOW need a fix ty for an awesome mod.

Ahhh I think I red it wrong, so pre 4 from optifine should work with the latest version of optifabric I reccon :D ? And if so where do I find the pre 4 link for download, can't find it anywhere.

Regards,

**Comment by juliavdkris** [comment]
@mucitrus I don't think you can download pre4 anymore, but pre13 is working fine with the latest GitHub pre-release of OptiFabric. https://github.com/modmuss50/OptiFabric/releases

**Comment by mucitrus** [comment]
@samvdkris It sure did, tyvm :)

**Comment by krypticcc** [comment]
@samvdkris i tried downloading it from that link, still not working. i am using the pre13 version of OptiFine. anything that i'm maybe not doing that you figured out while troubleshooting?

**Comment by mucitrus** [comment]
@krypticcc You need to have fabric and fabric api installed aswell to get it work, get latest versions and you should be fine :)

**Comment by krypticcc** [comment]
@mucitrus i do, i have a few other mods installed with the most recent fabric and fabric API, and these work fine.

**Comment by krypticcc** [comment]
@mucitrus nevermind, i was trying different things out and found that it did not work with a certain mod i had. now it works fine!

**Comment by MayliSong** [comment]
@krypticcc Which mod was it? I seem to be having a similar problem

**Comment by krypticcc** [comment]
@MayliSong it was immersive portals mod for me
