### ISSUE TITLE
"An unexpected critical error was encountered" at game startup (1.15.2)

### ISSUE THREAD

**Issue by 64-Tesseract** [modmuss50/OptiFabric#167]
As soon as the MC window appears, it crashes. Here's the log: https://pastebin.com/RvJDLtmP
Also, the launcher gives this message:
> The game crashed whilst initializing game
> Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

Doesn't look like there's much else I can do... I removed all my other mods, got rid of my old shaders, updated Fabric Launcher & API, but it still won't budge.

**Comment by modmuss50** [comment]
Update Optifabric you are using a really old version.

**Comment by 64-Tesseract** [comment]
What do you mean? The latest version on CurseForge is only 1.0.0-beta8! beta3 was the latest one available until somewhat recently.
