### ISSUE TITLE
More pictures

### ISSUE THREAD

**Issue by calloatti** [modmuss50/OptiFabric#17]
![2019-06-01_00 45 42](https://user-images.githubusercontent.com/12817862/58743448-af2b5180-8407-11e9-9cd0-d53d32fab2ad.png)

![2019-06-01_00 46 42](https://user-images.githubusercontent.com/12817862/58743452-c2d6b800-8407-11e9-9b34-04b1d3a2c8d8.png)

**Comment by duartenina** [comment]
What is that shader?

**Comment by calloatti** [comment]
https://sildurs-shaders.github.io/
