### ISSUE TITLE
Render Regions is not supported.

### ISSUE THREAD

**Issue by mibby** [modmuss50/OptiFabric#170]
Minecraft 1.15.2
Fabric 0.8.2+build.194
OptiFine 1.15.2 HD U G1 pre13
OptiFabric 1.0.0-beta8
phosphor-fabric-mc1.15.2-0.5.2+build.6

Using OptiFabric with the latest preview of Optifine for 1.15.2, OptiFabric outputs at the top ``OptiFabric: Render Regions is not supported!``. Would it be possible to support this Optifine feature or add an option to hide what isn't supported? 

Going into Options > Video Settings > Performance, I'm not able to toggle Render Regions setting. It is faded out as ON. I must go into the ``optionsof.txt`` file and manually set ``ofRenderRegions:false`` to turn it off / hide the warning.

**Comment by SpectrixDev** [comment]
This is still a major issue, I cannot toggle the setting on or off, it's grayed out. Makes OptiFabric unusable for me.

**Comment by NPC-112** [comment]
If you had read optifine's change log for his 1.15.2 releases, it says `not working: antialiasing, anisotropic filtering and render regions`

https://optifine.net/changelog?f=preview_OptiFine_1.15.2_HD_U_G1_pre14.jar

**Comment by modmuss50** [comment]
Removed this check
