### ISSUE TITLE
The game crashes as soon as I open it

### ISSUE THREAD

**Issue by IotaBread** [modmuss50/OptiFabric#175]
I'm using Optifabric beta 4 and optifine preview 13. Everytime I try to open the game, it crashes, but if I change the optifine version to the preview 9, it doesn't happen

**Comment by IotaBread** [comment]
Here is the crash report [crash-2020-04-14_20.48.46-client.txt](https://github.com/modmuss50/OptiFabric/files/4478355/crash-2020-04-14_20.48.46-client.txt)

**Comment by modmuss50** [comment]
update OptiFabric
