### ISSUE TITLE
1.15.2 Crashes on launch

### ISSUE THREAD

**Issue by MayliSong** [modmuss50/OptiFabric#177]
Using Minecraft 1.15.2, Fabric 0.8.2+build.194-1, FabricAPI 0.5.1+build.294, Optifabric 1.0.0-beta8, and Optifine 1.15.2_HD_U_G1_pre13.

The game loads ok with everything except Optifine, but if Optifine is added, the game crashes to launcher before it even gets a chance to load. Full crash report included.

https://pastebin.com/wN89pzT2

**Comment by MayliSong** [comment]
I discovered that the problem is caused by [I Need More Inventory Space](https://www.curseforge.com/minecraft/mc-mods/inmis), which is apparently a known problem on their end, [due to the Cardinal Components Item](https://github.com/Draylar/inmis/issues/10).

**Comment by HtoTheB** [comment]
I just tried to upgrade my optifine to this version and I had the same issue. U_G1_pre9 worked before and continues to be fine though, so it might be something to do with the current version...

**Comment by bellyrose** [comment]
mafficraft would you happen to have a link to pre9?

**Comment by ghost** [comment]
http://www.9minecraft.net/optifine-hd/
I have one.

**Comment by modmuss50** [comment]
Cardinal Components
