### ISSUE TITLE
Incompatible With Wurst

### ISSUE THREAD

**Issue by 1337Mishka** [modmuss50/OptiFabric#186]
I was recently using optifabric and optifine with the wurst client and despite not changing anything, my game starts having sudden seizures randomly and its become pretty much unplayable. The random seizures actually developed to the point where my game would freeze completely upon joining. Removing optifine and optifabric from my mod folder fixed the problem.

**Comment by hYdos** [comment]
the owner of optifabric does not support Wurst

**Comment by modmuss50** [comment]
Hacked clients arent supported
