### ISSUE TITLE
Render Regions Option is set to "ON" and not clickable  

### ISSUE THREAD

**Issue by ThunderShockBN** [modmuss50/OptiFabric#189]
As the title implies, I am not able to change this option even tho I clearly need to disable it to continue.
![javaw_IgAtYZfTYI](https://user-images.githubusercontent.com/34545846/80757386-12cf6a80-8b02-11ea-84f5-d83f083985fa.png)

**Comment by NPC-112** [comment]
open .minecraft\optionsof.txt and set `ofRenderRegions:true` to `false`

**Comment by ThunderShockBN** [comment]
Thanks! Also I want to mention that I attempted to ignore it and was able to play the game with render regions enabled, without any problem. No crashes, everything functioning as normal.

**Comment by modmuss50** [comment]
I will disable this check as it seems like its not supported in 1.15 optifine.
