### ISSUE TITLE
There was an error finding Optifine in the mods folder!

### ISSUE THREAD

**Issue by iamcurse** [modmuss50/OptiFabric#190]
![image](https://user-images.githubusercontent.com/28333142/80855997-619b1280-8c70-11ea-9a7b-5dea95864143.png)
![image](https://user-images.githubusercontent.com/28333142/80855998-64960300-8c70-11ea-8451-e95634c60604.png)
Help please, I already put optifine in mods folder but still not working.

**Comment by modmuss50** [comment]
1.14 is no longer supported, please try 1.15
