### ISSUE TITLE
Artifacts on Optifine 1.14.2 Pre7

### ISSUE THREAD

**Issue by chriexpe** [modmuss50/OptiFabric#20]
Having this strange issue..
Everything are on the latest version
File version/name: 
fabric-installer-0.4.2.27
fabric-api-0.3.0+build.170
preview_OptiFine_1.14.2_HD_U_F1_pre7
VoxelMap-1.9.4_for_1.14(.2)
Minecraft 1.14.2

![Base Profile Screenshot 2019 06 01 - 15 17 33 25](https://user-images.githubusercontent.com/16724821/58752149-85624100-8480-11e9-9168-6382312ebba8.png)
![Base Profile Screenshot 2019 06 01 - 15 17 42 90](https://user-images.githubusercontent.com/16724821/58752150-85624100-8480-11e9-8094-0f6dc0fd1fd9.png)
![Base Profile Screenshot 2019 06 01 - 15 17 50 54](https://user-images.githubusercontent.com/16724821/58752151-85fad780-8480-11e9-96a4-01443ca00501.png)

**Comment by calloatti** [comment]
fabric-api-0.3.0+build.170 is not latest version.

The solution to your problem, and the reason it happens can be found in the replies to other issues here.

Search for it and you will find it. There are only 18 issues total, so it's not that hard. And for the 2 minutes you spend reading older issues you will be rewarded with this:

![2019-06-01_00 46 42](https://user-images.githubusercontent.com/12817862/58743452-c2d6b800-8407-11e9-9b34-04b1d3a2c8d8.png)

**Comment by modmuss50** [comment]
Please read the readme, https://github.com/modmuss50/OptiFabric/blob/master/README.md

Shaders will not work.
