### ISSUE TITLE
Error : " java.lang.IndexOutOfBoundsException: bitIndex < 0: -1 " makes my game crash

### ISSUE THREAD

**Issue by TacoSeller420** [modmuss50/OptiFabric#204]
Whenever I perform a /n spawn or /t spawn command (basically tp) My game will always crash over and over again until i remove Optifabrics out of my mods folder. 
![bruhwtfisthat](https://user-images.githubusercontent.com/54733311/82113374-8dfc6780-9723-11ea-8a88-7b4e3257452c.png)

I am using preview_OptiFine_1.15.2_HD_U_G1_pre7.jar and optifabric-1.0.0-beta4.jar

one of my friend also use the same versions and doesnt seem to encounter that problem.

**Comment by modmuss50** [comment]
update optifabric and optifine
