### ISSUE TITLE
It Needs to be updated so it works with. OptiFine 1.15.2 HD U G1 pre17

### ISSUE THREAD

**Issue by ghost** [modmuss50/OptiFabric#205]
Please Update so it works with: OptiFine 1.15.2 HD U G1 pre17

**Comment by 0xfeeddeadbeef** [comment]
It already does work with pre17. No update needed.

**Comment by ghost** [comment]
But my game keeps crashing

**Comment by 0xfeeddeadbeef** [comment]
Get the latest crash report from `%AppData%\.minecraft\crash-reports\` folder and post it here.
It is possible that the source of crash is other mod.

**Comment by ghost** [comment]
i found out why it crashed for like a minute ago

**Comment by ghost** [comment]
It were an outdated mod
