### ISSUE TITLE
1.15.2 doesn't work...?

### ISSUE THREAD

**Issue by TheBoiPotato** [modmuss50/OptiFabric#206]
I want to use OptiFabric for 1.15.2, but optifine 1.15.2 doesn't exist/I can't find one online. I there optifine 1,15,2?

**Comment by 0xfeeddeadbeef** [comment]
Click on [**Preview versions**](https://optifine.net/downloads) link and you'll find it.
Here's a direct link to latest version: http://optifine.net/adloadx?f=preview_OptiFine_1.15.2_HD_U_G1_pre17.jar

**Comment by TheBoiPotato** [comment]
Ohhhh Okay. I didn't see that button on the website. Thank you.

**Comment by 0xfeeddeadbeef** [comment]
@TheBoiPotato You may as well close this issue.
