### ISSUE TITLE
Connected Textures Broken

### ISSUE THREAD

**Issue by fantahund** [modmuss50/OptiFabric#22]
Unfortunately, Connected Textures does not work with Optifabric. Please fix. :)

![Screenshot_107](https://user-images.githubusercontent.com/42190420/58933671-60175080-8768-11e9-9158-0bd614929681.png)

**Comment by lightking813** [comment]
It's still bugged
![image](https://user-images.githubusercontent.com/49906237/69912639-f666cd80-1490-11ea-9225-5c2ebe67626e.png)
![image](https://user-images.githubusercontent.com/49906237/69912660-5e1d1880-1491-11ea-885e-4997751a99e0.png)
