### ISSUE TITLE
Either OptiFine or OptiFabric is incompatible with fabric-api 317

### ISSUE THREAD

**Issue by keuin** [modmuss50/OptiFabric#220]
I'm playing Minecraft 1.15.2. After trying a lot of different versions of fabric-api, I find that either OptiFabric or Optifine is not compatible with the latest fabric api (for mc 1.15.2) 317. The game just crashes when I open a singleplayer world or join a server.
I tried OptiFine G1 pre9, pre18, pre28 and pre30, OptiFabric 1.0.0-beta4 and 1.0.0-beta8, the problem is not concerned with the OptiFine version
 and OptiFabric version.
However, it works smoothly with fabric api 316. The version of fabric-loader I'm using is 202, and an older version 194 also works. So the problem seems to be related with the fabric-api update (from 316 to 317).
If so, please fix the compatibility with fabric-api 317.
The error log is provided in the attachment.

(Sorry for editing so many times, the incompatible version is 317, not 316)

[minecraft-exported-logs-2020-06-27T11-10-34.log](https://github.com/modmuss50/OptiFabric/files/4839945/minecraft-exported-logs-2020-06-27T11-10-34.log)

**Comment by EricKilla** [comment]
I can confirm this incompatibility.

**Comment by modmuss50** [comment]
I have seen reports of this, I will take a look to see what I can do about it.

Thanks for waiting.
