### ISSUE TITLE
Crash to desktop on launch when used with Light Overlay or Roughly Enough Items (1.16.1)

### ISSUE THREAD

**Issue by ilepow34** [modmuss50/OptiFabric#223]
When using Optifabric with either of Roughly Enough Items or Light Overlay (or both) the game crashes almost immediately after the loading screen finishes. The same exception is thrown for both. It occurs with the following installed:

- Minecraft 1.16.1
- Fabric Loader 0.8.9 build 203
- Fabric API 0.14.1 build 372
- Optifine 1.16.1 HD U G2 pre1
- Optifabric 1.1.0 beta1
- Light Overlay 5.4.0 and/or Roughly Enough Items 4.6.6

I attached the crash reports from running the game with each mod individually, and the full log associated with the Light Overlay crash report.

[Light-Overlay.txt](https://github.com/modmuss50/OptiFabric/files/4871065/Light-Overlay.txt)
[Roughly-Enough-Items.txt](https://github.com/modmuss50/OptiFabric/files/4871066/Roughly-Enough-Items.txt)
[latest.log](https://github.com/modmuss50/OptiFabric/files/4871063/latest.log)

**Comment by modmuss50** [comment]
Can confirm, seems to be coming from: 

https://github.com/shedaniel/cloth-api/blob/3913836e59e1df9058ece3e791ee0f5993b8bc00/cloth-client-events-v0/src/main/java/me/shedaniel/cloth/mixin/client/events/MixinGameRenderer.java#L49

Its not a trivial fix, but ill try my best.

**Comment by modmuss50** [comment]
Fixed, please update to beta2
