### ISSUE TITLE
Freeze on main menu (1.16.1)

### ISSUE THREAD

**Issue by Zano1999** [modmuss50/OptiFabric#227]
The game's freeze (don't respond) when the menu is loaded

**Comment by modmuss50** [comment]
is there a crash log? what mods do you have? does it happen with no mods?

**Comment by Zano1999** [comment]
[crash.pdf](https://github.com/modmuss50/OptiFabric/files/4871514/crash.pdf)

**Comment by modmuss50** [comment]
Please try updating to beta 2

**Comment by Zano1999** [comment]
tnx,now it work!
