### ISSUE TITLE
[Solved] In Game Toolbar/GUI Graphics Missing [1.16.1]

### ISSUE THREAD

**Issue by Slycan** [modmuss50/OptiFabric#229]
Solved: Updated to Optifine 1.16.1 **Preview 2**
Minecraft version 1.16.1
Optifabric 1.1.0 BETA 2
Optifine Preview 1.16.1 PRE1
Fabric API 0.14.1 Build 372
Mod Menu 1.12.2 Build 17

![optifine116test1](https://user-images.githubusercontent.com/53203587/86498676-baa02900-bd3b-11ea-87cc-51027dadb237.png)

**Comment by rosalinadev** [comment]
Doesn't happen to me, have you got any resourcepacks on and did you reset your video settings?

**Comment by rosalinadev** [comment]
Update to Optifine pre2

[Changelog](https://optifine.net/changelog?f=preview_OptiFine_1.16.1_HD_U_G2_pre2.jar)
> OptiFine 1.16.1_HD_U_G2_pre2
>  \- not working: antialiasing, anisotropic filtering and render regions
>  \- added Entity Distance in performance options (#4206)
>  \- **fixed white hotbar with shaders and FXAA** (#4201)
>  \- updated to 1.16.1
>  \- compatible with Forge 32.0.25
> (03.07.2020)

**Comment by Slycan** [comment]
Fixed! Thankies
