### ISSUE TITLE
[Workaround] Shaders not working/visual glitch workaround

### ISSUE THREAD

**Issue by SynexWolf** [modmuss50/OptiFabric#23]
The current workaround I have used is to edit the "indigo-renderer.properties" in fabric's config (.minecraft\config\fabric). You want to change "always-tesselate-blocks=auto" to "always-tesselate-blocks=false" and "ambient-occlusion-mode=enhanced" to "ambient-occlusion-mode=vanilla".

**Comment by Motschen** [comment]
Works perfectly for me! Thank you for letting others know how to fix the issue so easily 👍 😃

**Comment by modmuss50** [comment]
This will for for a bit, but will cause issues if mods start to require this feature.
