### ISSUE TITLE
1.14.2 Fire not animated Opfitine pre9

### ISSUE THREAD

**Issue by ghost** [modmuss50/OptiFabric#24]
Fire isn't animated. Might be normal Optifine, but has happened with multiple Optifine pre-releases, like 8 as well. I understand if you can't get to it or if you don't have the drive to, so I'd like to thank you guys for your awesome mod anyways! :)

**Comment by modmuss50** [comment]
Seems to work fine for me on the new 1.14.3 version. Can you test again please?

**Comment by ghost** [comment]
Can still reproduce on the full release of HD F1 U and Optifabric 0.3.1
Portal animations also don't seem to work

**Comment by modmuss50** [comment]
Humm, are you using shaders?

If not can you try setting shaders to internal?

**Comment by ghost** [comment]
Setting shaders to internal does fix this, and #33 also seems to be fixed

**Comment by modmuss50** [comment]
Humm, thanks for testing that I will change the workaround to always be enabled, as right now the workaround is only enabled with shaders

**Comment by modmuss50** [comment]
Should be fixed in OptiFabric 0.3.2
