### ISSUE TITLE
Block textures do not load

### ISSUE THREAD

**Issue by Stedal24** [modmuss50/OptiFabric#26]
It seems that whenever I install optic fabric on my version of Minecraft (1.14.2), I experience a large issue with the graphics. No block textures load at all, the only textures visible are the skybox, particles, and entities. For reference, the version of optifabric I am using is 0.2.0, and I am using the 1.14.2 HD U F1 pre13 version of Optifine. This graphical glitch only occurs when the jar file is placed into the mods folder, and it makes the entire game unplayable. The URL below will bring you to a screenshot I have taken with the mod activated.

![Graphical Error](https://user-images.githubusercontent.com/51935431/59645685-19dacd80-9128-11e9-9c3f-1a7c546723bf.png)

**Comment by modmuss50** [comment]
Can you try the new version for 1.14.3. I am not able to reproduce this issue.

**Comment by itsCryne** [comment]
Can repro, MC 1.14.3, Fabric 0.4.8+build.155, Fabric-API 0.3.0+build.187, Optifabric 0.3.0 and Optifine 1.14.3_HD_U_F1, some (only really few) chunks are loaded, but only to a really low height.
But it seems like it has to do something with a graphic setting as when I reset mine all worked correctly...

**Comment by itsCryne** [comment]
Ah... seems like this bug only occurs if Render-regions is enabled

**Comment by modmuss50** [comment]
Yes, I can repoduce. I will add a warning

**Comment by modmuss50** [comment]
![](https://ss.modmuss50.me/java_2019-06-29_18-06-50.png)

This should help, thanks for reporting.

**Comment by itsCryne** [comment]
Seems like it got fixed on the way to/in 0.5.1, cant repro it anymore @modmuss50
