### ISSUE TITLE
Need update to support 1.14.3 OptiFine

### ISSUE THREAD

**Issue by eternitymoe** [modmuss50/OptiFabric#27]
Version 0.2.1 & 0.2.0 are unable find optifine jar when running on MC 1.14.3.
Please update it.
<img width="797" alt="Screenshot 2019-06-27 at 05 47 27" src="https://user-images.githubusercontent.com/44344308/60217494-6f894580-989f-11e9-8ad5-600b4dc550d0.png">

**Comment by bonn2** [comment]
Submitted a pull request with a fix. Pull #28

**Comment by calloatti** [comment]
https://github.com/schamane/OptiFabric/releases

**Comment by eternitymoe** [comment]
Using schamane/OptiFabric/releases and work good.
