### ISSUE TITLE
Licensing Suggestion

### ISSUE THREAD

**Issue by CobaltSpace** [modmuss50/OptiFabric#29]
Hello there.  You have suggested that optifine incorporate the code of this project into optifine.  As it stands, they currently can not do that due to an incompatibility in licensing.

Basically, If you want them to use this code, all contributors to this project are going to need to agree to give to Optifine a non-revocable license to do whatever they want with the code.  You could also agree to re license under MIT.

**Comment by MissPotato** [comment]
You might need to reach out to ModMuss50 on twitter at https://twitter.com/modmuss50 or by joining their discord at discord.gg/teamreborn. It doesn't seem like they're paying too close attention to this GitHub as it's an abandoned project.

**Comment by modmuss50** [comment]
If the optifine developer wants to use some of the code I am availablein multiple places (twitter/disord/email) and would be willing to come to an agreement I would be happy to talk!
