### ISSUE TITLE
Can't find net/minecraft/class_2561

### ISSUE THREAD

**Issue by oliviathevampire** [modmuss50/OptiFabric#31]
Chrashlog https://gist.github.com/sindrefag/cb154da13270f70d606c839aee804c0b

**Comment by SteveKunG** [comment]
Seems work fine to me, Some installed mods broke your game?

![2019-06-28_21 30 58](https://user-images.githubusercontent.com/6128413/60349554-0c58f980-99ec-11e9-9696-de206cae2138.png)

**Comment by oliviathevampire** [comment]
@SteveKunG you can see my mods in the modlist in the chrash report

**Comment by oliviathevampire** [comment]
This version worked for me atleast https://github.com/schamane/OptiFabric/releases

**Comment by modmuss50** [comment]
I don’t think this is an optifabric issue. Try reinstalling fabric
