### ISSUE TITLE
1.14.3 Connected Textures don't display

### ISSUE THREAD

**Issue by KleinGrrmpf** [modmuss50/OptiFabric#33]
As the title says, the ctm folder isn't working when using OptiFabric. With an optifine profile the ctm works fine, but if you use fabric and OptiFabric it doesn't.

**Comment by KleinGrrmpf** [comment]
neither do transistions

**Comment by modmuss50** [comment]
Can you try setting shaders to internal to see if this solves the isssue, if it does I may tweak some of my work arounds.

**Comment by modmuss50** [comment]
Should be fixed in OptiFabric 0.3.2
