### ISSUE TITLE
CTD on Fresh Fabric Install 1.14.3 B9

### ISSUE THREAD

**Issue by Tkdmaster** [modmuss50/OptiFabric#34]
Getting a crash on launch with latest CurseForge version of Optifabric (0.3.1) and latest/fresh Fabric install (1.14.3 B9).

Here is the crashlog:

https://pastebin.com/jX6bmXbi

Please let me know if you need anything else!

**Comment by modmuss50** [comment]
Do you have the optifine jar in the mods folder?

If you do could you post the full log please, this could possibly be a regression with the error handling.

**Comment by Tkdmaster** [comment]
I don't have Optifine itself installed currently, just the OptiFabric jar.

**Comment by modmuss50** [comment]
Ah, that explains it. You need to put the optifine jar in the mods folder.

This is still a bug however as it should show an error message

**Comment by modmuss50** [comment]
Fixed in optifabric 0.3.2
