### ISSUE TITLE
Render Regions Not Supported

### ISSUE THREAD

**Issue by Barerock** [modmuss50/OptiFabric#38]
The error appears on the title menu on the top left and says:
"OptiFabric: Render Regions is not supported!"
My mod list is as follows:
1. Fabric API 0.3.0 build 191
2. Antique Atlas 5.0.6
3. Biomes O' Plenty 1.14.3-9.0.0.173
4. OptiFabric 0.4.0
5. The Biome Overhaul 1.2.1
6. Optifine 1.14.3_HD_U_F1_MOD

**Comment by modmuss50** [comment]
Turn of Render Regions in the Video settings, like the message says its not supported.
