### ISSUE TITLE
Installed Optifine this way and became Picasso?

### ISSUE THREAD

**Issue by Luth0r** [modmuss50/OptiFabric#41]
https://cdn.discordapp.com/attachments/592799037456121871/599056243243483157/unknown.png

i did everything as instructed... help

**Comment by modmuss50** [comment]
What version of the mod are you using? it seems like an old one as this should have been fixed.

You will need to also update to 1.14.3 as well to get the fix.

**Comment by Luth0r** [comment]
The thing is, Optifine works perfectly. The issue is only with the shaders.

**Comment by modmuss50** [comment]
Yes, this exact issues has been fixed.
