### ISSUE TITLE
OptiFine sliders are broken

### ISSUE THREAD

**Issue by ArtelGG** [modmuss50/OptiFabric#42]
Changing a slider then clicking on any empty space results in you still changing the slider.

_https://youtu.be/euvq7vFnHiQ_

**Comment by calloatti** [comment]
Optifine by itself does the exact same thing when installed using the optifine installer in a Vanilla launcher instance, so not an Optifabric problem.

Report to https://github.com/sp614x/optifine/issues


![of](https://user-images.githubusercontent.com/12817862/61141366-d0ba3700-a4a3-11e9-8c0b-7d5338dca4c8.gif)
