### ISSUE TITLE
Gamecrash with latest optifine F2 pre3 while booting

### ISSUE THREAD

**Issue by bonn2** [modmuss50/OptiFabric#43]
When I attempt to run with the latest Optifine (F2 pre3) the game crashes and fails to launch altogether.

Crashlog
https://pastebin.com/LszQgcLp

This version is the first to include the beginning of Forge support, could it be related?
It also has some changes to shaders and translations but I doubt those would prevent it from launching like this.

**Comment by calloatti** [comment]
My advice: just use OptiFine 1.14.3 HD U F1 for now. By the time those preview versions of optifine become an actual release, MC will be in 1.14.4 or 5

**Comment by modmuss50** [comment]
Thanks for reporting this, I will look into it when I get a chance.

**Comment by modmuss50** [comment]
Ok, optifine has made some fairly large changes to the ChunkRenderer that are not compatible with Fabric's Indigo renderer.

I think its going to be possible to fix but will take some work from me.

**Comment by modmuss50** [comment]
Fixed, update to optifabric 0.4.2. Thanks for reporting.
