### ISSUE TITLE
PBR textures not working on netherthings basalt

### ISSUE THREAD

**Issue by Nathan22211** [modmuss50/OptiFabric#48]
PBR is working fine on netherrack, but upon attempting a similer result on basalt no luck. i'll include the files in the zip so you can test them to try to get it to work
[files.zip](https://github.com/modmuss50/OptiFabric/files/3427924/files.zip)

**Comment by Nathan22211** [comment]
I haven't tested the labPBR standard yet so I'll have to check if that's working, and I can't test SUES's standard as I have an Intel APU

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
