### ISSUE TITLE
optifabric: render regions is not supported

### ISSUE THREAD

**Issue by PSILONCRAFT** [modmuss50/OptiFabric#49]
have the following mods installed
fabric-api-0.3.0+build.206
optifabric-0.4.3
OptiFine_1.14.4_HD_U_F2
1.14.4 fabric client

**Comment by modmuss50** [comment]
Disable Render Regions in settings, its not supported...

**Comment by McInnescraft** [comment]
Thank you, had no idea why it was showing that
