### ISSUE TITLE
Textures broken

### ISSUE THREAD

**Issue by AedanBeisly** [modmuss50/OptiFabric#50]
So I'm using optifabric 0.2.0, optifine for 1.14.2, fabric api 0.3.0 and replaymod 1.14.2.
For some reason with optifabric, minecraft is reading the textures wrong and so I get textures only on one side of each block and the texture is from the completely wrong place, eg, part of a melon block on the grass block. I've tried reinstalling everything several times with no luck, any idea what is wrong?
![2019-07-27_11 39 10](https://user-images.githubusercontent.com/24219665/61986452-46f19880-b063-11e9-932d-7a505f19af2c.png)
It does this with both default and custom texture packs

**Comment by modmuss50** [comment]
Update optifabric to 1.14.4 to fix this.-
