### ISSUE TITLE
1.14.4 launch hanging

### ISSUE THREAD

**Issue by NullEntity** [modmuss50/OptiFabric#51]
I'm trying out OptiFabric with OptiFine_1.14.4_HD_U_F2. It seems to hang on remapping Optifine. Here's my launch log:
https://paste.ee/p/KfG2m

**Comment by calloatti** [comment]
Test with Java 8 and see if it works. (it may/may not be that, but it never hurts to try)

**Comment by NullEntity** [comment]
I'm not really sure what's going on. With Oracle's 32 bit JRE and AdoptOpenJDK's 64 bit JRE, Optifabric seems to not be loaded. The game is launching properly, but without Optifine loaded. Here's another launch log:
https://paste.ee/p/R6FnW

**Comment by calloatti** [comment]
after switching java, delete the .fabric and .optifine folders so they regenerate. The "no mods seem to load" is fixed by deleting the .fabric folder.

**Comment by calloatti** [comment]
You may want to add https://www.curseforge.com/minecraft/mc-mods/modmenu to get a "mods" button on the main menu.

Also, the fabric discord server for general support is an option too: https://discordapp.com/invite/v6v4pMv

**Comment by calloatti** [comment]
Issue solved in the Fabric Discord so it can be closed.
