### ISSUE TITLE
i installed Optifabric and optfine 1.14.4 

### ISSUE THREAD

**Issue by SiloMiloYT** [modmuss50/OptiFabric#53]
Hello, so I installed Optifabric and optifine 1.14.4 and forge 1.14.4 then when I opened it said
optifabric cannot be loaded and optifine
![Capture](https://user-images.githubusercontent.com/53516237/62202687-6d307480-b392-11e9-855b-3431598fc754.PNG)

How can i fix this ???

**Comment by calloatti** [comment]
Optifabric is a Fabric mod, not a Forge mod. 

https://fabricmc.net/wiki/doku.php
https://fabricmc.net/

**Comment by SiloMiloYT** [comment]
ya i figured it out i forgot about this post thanks anyway
