### ISSUE TITLE
OpftiFabric cannot find the Opftine mod (1.14.4)

### ISSUE THREAD

**Issue by Zolo101** [modmuss50/OptiFabric#54]
OpftiFabric cannot find the Opftine mod. [What it looks like in minecraft](https://i.imgur.com/uzjt6Ue.png)
[What my directories look like](https://i.imgur.com/GR91ABQ.png)

**Comment by calloatti** [comment]
Where did you download that optifine file from?

This is the name and size of the real file:

![image](https://user-images.githubusercontent.com/12817862/62341191-bb3f9800-b4b8-11e9-8469-3290b42a5944.png)

Download it from https://www.optifine.net/downloads

**Comment by Zolo101** [comment]
Oh, that might of been the problem, when redownloading i got a 2 MB file instead of 24 MB. It seems to have worked now.
