### ISSUE TITLE
Water Colormaps not working

### ISSUE THREAD

**Issue by BotMeat** [modmuss50/OptiFabric#56]
I use a resource pack with custom water colormaps. it only works with optifine. However, while using optifabric, it causes it to use the default water colormap.

![2019-08-06_10 52 29](https://user-images.githubusercontent.com/53829391/62552755-2fbd6280-b83c-11e9-9f18-e618b26c037d.png)
With optifabric

![2019-08-06_10 53 40](https://user-images.githubusercontent.com/53829391/62552783-35b34380-b83c-11e9-92a7-04be74c6288a.png)
Without optifabric

**Comment by josephrooks** [comment]
Possibly related, "swamp colors off" in Optifine works for grass and leaves but doesn't work for water.

**Comment by SimoneComitini** [comment]
Is there a way to fix this?

**Comment by Stonehawk** [comment]
Want to corroborate: this is still unresolved as of the previous version update. 
![image](https://user-images.githubusercontent.com/2092291/67054002-22143b00-f111-11e9-94e4-0243e31981eb.png)
![image](https://user-images.githubusercontent.com/2092291/67054009-293b4900-f111-11e9-80d9-7625c0a48d1e.png)

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.

**Comment by MamiyaOtaru** [comment]
that's cool and all but the issue persists in 1.15.2.  water colormaps are just ignored with optifine+optifabric, while with optifine alone they work as expected
