### ISSUE TITLE
Feature request: Allow game to start when optifine is not found

### ISSUE THREAD

**Issue by calloatti** [modmuss50/OptiFabric#57]
When optifabric does not find the optifine jar in the mods folder, right now it does not allow the game to start.

![image](https://user-images.githubusercontent.com/12817862/62625224-2ba44a00-b8fb-11e9-91ca-841eb0852d94.png)

It would be more convenient if optifabric allowed the game the continue loading without optifine, if possible.

This request is due to the fact that the optifine jar cannot be included in a modpack and we are planning an AOF Vanilla+ modpack release with optifabric, and players will have to manually download optifine if they want it. 

Another option could be for the error screen to just include a button with a link to the opfitine download page?

The intention is to simplify things for players, like having to disable optifabric to make the instance work.

**Comment by modmuss50** [comment]
Adding a link to the download page, yes.

But it will always fail to load, as people may install the mod and expect it to work, sorry.

**Comment by calloatti** [comment]
Maybe a config option for modpack makers then? 

> optifabric allowed the game the continue loading without optifine

Just to clarify: The request is not for optifabric to silently fail, but to have an additional button in the error screen, maybe something like  `Continue without Optifine` or something like that.

**Comment by Mhowser** [comment]
> Just to clarify: The request is not for optifabric to silently fail, but to have an additional button in the error screen, maybe something like `Continue without Optifine` or something like that.

This is the best solution.

**Comment by modmuss50** [comment]
I get your point, but I still dont think its a good idea becuase Optifabric apply's some mixins to fabric and the base game that assume that optifine is installed and working corectally. Having it in a known good or bad state is better imo, and not having it in some 1/2 applied state.

**Comment by calloatti** [comment]
Ok I understand. I will just add a note mentioning that the pack supports optifabric and optifine and players have to download and install them.
