### ISSUE TITLE
AoF crash

### ISSUE THREAD

**Issue by BernardoGrigiastro** [modmuss50/OptiFabric#59]
All of Fabric crashing with latest optifabric and optifine

https://pastebin.com/4PsfMPH2

**Comment by modmuss50** [comment]
Can you try without Arcane Magic, as its been known to have issues in the past.

**Comment by BernardoGrigiastro** [comment]
It works without Arcane Magic, shame such a nice mod...
![2019-08-18_17 52 35](https://user-images.githubusercontent.com/47037877/63226982-dcda9800-c1b7-11e9-91ac-96c954c47ebe.png)
