### ISSUE TITLE
Doesn't work in 1.14.4 I did everything I could.

### ISSUE THREAD

**Issue by ItsNickXD** [modmuss50/OptiFabric#60]

**Comment by modmuss50** [comment]
Does it show an error? anything I can go off to try and help you?

**Comment by calloatti** [comment]
Follow the tutorial here: https://github.com/modmuss50/OptiFabric/wiki/Install-Tutorial

**Comment by Jas-GRE** [comment]
Same for me.Followed the tutorial and look what it says
![image](https://user-images.githubusercontent.com/54215479/63214891-03042780-c127-11e9-864e-515475edb083.png)

**Comment by calloatti** [comment]
Well, you are trying to use the fabric api, optifabric and optifine in a Forge instance...

Fabric is a mod loader incompatible with Forge (another mod loader).

Start here: https://fabricmc.net/
