### ISSUE TITLE
Visual glitches with Orderly

### ISSUE THREAD

**Issue by UpcraftLP** [modmuss50/OptiFabric#62]
see https://github.com/UpcraftLP/Orderly/issues/2, as well as some crash (https://github.com/UpcraftLP/Orderly/issues/3), but I haven't yet reproduced that one.

**Comment by modmuss50** [comment]
Not sure what im able to do about this tbh.

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.

**Comment by UpcraftLP** [comment]
possibly still relevant in 1.15, haven't tried it yet.
