### ISSUE TITLE
with tech reborn crashes

### ISSUE THREAD

**Issue by lkreite** [modmuss50/OptiFabric#64]
1) with versions of techreborn of 8 august and before crashes on watching of crafts
2) with versions of techreborn after 8 august just crashes on starting of minecraft
[crash-2019-08-29_22.28.14-client.txt](https://github.com/modmuss50/OptiFabric/files/3557237/crash-2019-08-29_22.28.14-client.txt)
"The game crashed whilst rendering item
Error: java.lang.NullPointerException: Rendering item"

**Comment by modmuss50** [comment]
update techreborn
