### ISSUE TITLE
Cannot open with optifine

### ISSUE THREAD

**Issue by boiimakillu** [modmuss50/OptiFabric#65]
[latest.log](https://github.com/modmuss50/OptiFabric/files/3572578/latest.log)
[2019-09-03-6.log.gz](https://github.com/modmuss50/OptiFabric/files/3572583/2019-09-03-6.log.gz)
Whenever I try to launch with optifine and optifabric, it gives me an error and doesnt let me launch. It just says there was a crash.

**Comment by modmuss50** [comment]
the log seems to be missing a lot of infomation

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
