### ISSUE TITLE
I can't open minecraft with optifabric

### ISSUE THREAD

**Issue by Hernandou** [modmuss50/OptiFabric#66]
Hello, I recently installed optifabric and when I try to start Minecraft this error occurs, I searched many forums and I could not fix it, thank you very much in advance
![Sin título](https://user-images.githubusercontent.com/54945256/64347134-c7dc7200-cfc9-11e9-8f7c-691d1801d7e3.jpg)

**Comment by calloatti** [comment]
Minecraft version? Optifabric version? Optifine version?

**Comment by Hernandou** [comment]
minecraft 1.4, optifabric version 1.14 and optifine version 1.14

**Comment by calloatti** [comment]
So this optifine version? `OptiFine 1.14 HD U F1 pre6`

There are 3 files optifabric for 1.14 : optifabric-0.1.0.jar, optifabric-0.1.1.jar, optifabric-0.1.3.jar. You will have to be more specific.

MInecraft 1.4? I dont think 1.14 versions of Optifabric, Optifine, or Fabric loader will work on MC 1.4

**Comment by modmuss50** [comment]
please update to 1.14.4 and try again. if you can repoduce on that version please open a new issue along with the log.
