### ISSUE TITLE
Unable to Delete Optifine-mapped.jar

### ISSUE THREAD

**Issue by roraraptor** [modmuss50/OptiFabric#69]
When I launch Minecraft I get an error saying `java.io.IOException: Unable to delete file: .\.optifine\OptiFine_1.14.4_HD_U_F3\Optifine-mapped.jar`.

**Log:** [latest.log](https://github.com/modmuss50/OptiFabric/files/3586938/latest.log)

# System
**OS:** Windows 10 Home, Version 1903, Build 18362.295
**Java:** 1.8.0_221, 64-bit

# Minecraft
**Fabric:** Fabric Mod Loader (0.4.8+build.159, 1.14.4+build.12) installed using MultiMC (0.6.7-1375) as a fresh instance.

**Installed mods:**
* Fabric API (0.3.1+build.208)
* OptiFabric (0.5.1)
* OptiFine (1.14.4 HD U F3)

**Comment by modmuss50** [comment]
Humm, is that file possibly loked by another application?

**Comment by roraraptor** [comment]
@modmuss50 I don't think so, although I don't know how I would check that. I have tried running everything as an administrator as well, with no luck. If there is anything specific I could do to get further details that would help solve the problem, please let me know.

**Comment by TheK0tYaRa** [comment]
Try installing minecraft in the root of the drive and if that doesn't help then it's not a rights problem but an antivirus problem.

**Comment by roraraptor** [comment]
My issue was solved. It was indeed an antivirus problem. I told Immunet to install first and then check, and it worked fine. I was fooled because Immunet didn't report any issues, but I guess the check itself was enough to break the setup process.
