### ISSUE TITLE
JVM Arguments for Optifine are not executed upon startup

### ISSUE THREAD

**Issue by Nex-Stargaze** [modmuss50/OptiFabric#70]
I learned about a sort of secret method to get custom models onto players and in order to do it, I had to set up some extra JVM arguments in the MC launcher, as a result...

https://cdn.discordapp.com/attachments/423430686880301060/621006304042942464/unknown.png

It wouldn't appear. I thought it was a bug on the side of the model and config itself but... I instead had to launch Optifine through the launcher itself and not through Fabric's Optifabric for the function to work

https://cdn.discordapp.com/attachments/423430686880301060/621010794183655449/unknown.png

I'm glad its working.... but I can't abandon my radars and other cool features from fabric, do you know of a way to have JVM arguments take place after the launching of fabric/optifabric to apply to this?

To reproduce this, I'd suggest downloading this example zip of how the function works and read the readmepls.txt for all directions.

[optifineplayermodels.zip](https://github.com/modmuss50/OptiFabric/files/3596743/optifineplayermodels.zip)

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
