### ISSUE TITLE
How to disable persistent error message

### ISSUE THREAD

**Issue by Flexico** [modmuss50/OptiFabric#77]
Whenever I play the game, there's a red message at the top left saying: "Optifabric: Render Regions not supported!" that is there any time I'm in a menu or inventory. I'm not sure what it means, but I assume it's some feature of Optifine that isn't working, which is fine; I just want the error message to go away.
MC 1.14.4
Fabric 0.6.2-build.166
Optifine HD U F3

**Comment by Keysandrew** [comment]
It's caused by having the "Render Regions" options under the "Performance" tab in the Video Settings. As far as I understand, there is currently a compatibility issue with the Render Regions option. I'm sure exactly what the problem is, but I'd recommend switching the setting to off.

**Comment by Flexico** [comment]
Aahh, there we go! Thank you~
