### ISSUE TITLE
Minecraft crashing because of optifabric

### ISSUE THREAD

**Issue by Andrew963** [modmuss50/OptiFabric#79]
Sometimes my game crashes and the crash report says it was caused by Batching Chunks sp614x said its problem with optifabric not optifine
 
here is the crash report:

Time: 13.10.2019 18:22
Description: Batching chunks

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at net.minecraft.class_853.handler$init$zbj000(class_853.java:1045)
	at net.minecraft.class_853.<init>(class_853.java:108)
	at net.minecraft.class_853.generateCache(class_853.java:90)
	at net.minecraft.class_851.createRegionRenderCache(class_851.java:785)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:774)
	at net.minecraft.class_851.method_3652(class_851.java:256)
	at net.minecraft.class_845.method_3615(class_845.java:90)
	at net.minecraft.class_845.run(class_845.java:39)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at net.minecraft.class_853.handler$init$zbj000(class_853.java:1045)
	at net.minecraft.class_853.<init>(class_853.java:108)
	at net.minecraft.class_853.generateCache(class_853.java:90)
	at net.minecraft.class_851.createRegionRenderCache(class_851.java:785)
	at net.minecraft.class_851.makeChunkCacheOF(class_851.java:774)

-- Affected level --
Details:
	All players: 1 total; [class_746['Andrew_369'/262196, l='MpServer', x=3316.50, y=63.00, z=-1842.50]]
	Chunk stats: Client Chunk Cache: 729, 645
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 173694938 game time, 167004429 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:9e76966:1420) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_845.run(class_845.java:45)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 856932608 bytes (817 MB) / 1731723264 bytes (1651 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G
	Fabric Mods: 
		appleskin: AppleSkin 1.0.7
		fabric: Fabric API 0.3.0+build.200
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb42
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c5242
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c5242
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b7542
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+5914746342
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+ea100f6142
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+5914746342
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c42
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa642
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+ab421b9c42
		fabric-models-v0: fabric-models-v0 0.1.0+5914746342
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c5242
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+592d1d2242
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+ea100f6142
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.1+9486cfbf42
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.9+9486cfbf42
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b42
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c242
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e42
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c42
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c3542
		fabricloader: Fabric Loader 0.4.8+build.157
		litematica: Litematica 0.0.0-dev.20190720.191654
		malilib: MaLiLib 0.10.0-dev.20
		minihud: MiniHUD 0.19.0-dev.20190720.191339
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.7.6+build.115
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.5.2
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		replaymod: Replay Mod 1.14.4-2.2.0-b7
		voxelmap: VoxelMap 1.9.13
		worldedit: WorldEdit 7.0.1;61bc012
	Launched Version: fabric-loader-0.4.8+build.157-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Silent Dispensers.zip, file/KelpRemover.zip, file/VanillaTweaks_r635532.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz

**Comment by realskudd** [comment]
I too experienced this issue. Worth noting: it's happening more frequently with newer versions of opti(fine|fabric), while OptiFabric 0.4.3 + OptiFine 1.14.4 F2 pre1 doesn't experience it as often.

It seems like this happens a lot when there are a lot of items around, either laying on the ground or in hoppers. I have a carpet duper running over a grid of hoppers, piped into other hoppers, into an array of furnaces. I think the high volume of carpet items is triggering this.

**Comment by Andrew963** [comment]
it happens to me when teleporting to my base with lot of hopper (because of
sitting system) and there is lot of item frames too i think it has to do
something with rendering or smoothlight because when it crashes you can see
for a second glitched light everywhere and all chest are invisible


ut 15. 10. 2019 o 3:02 Tim Garrison <notifications@github.com> napísal(a):

**Comment by Andrew963** [comment]
*sorting system


ut 15. 10. 2019 o 18:56 Andrew WithNoLife <mrpoulik@gmail.com> napísal(a):

**Comment by modmuss50** [comment]
Your all using really old versions, update FabricAPI and Optifabric

Use this version of fabric api: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2810785

This crash was fixed a while ago

**Comment by Andrew963** [comment]
now its crashing when i start the game and it doenst even give me crash
report


pi 18. 10. 2019 o 19:42 Mark J <notifications@github.com> napísal(a):
