### ISSUE TITLE
Shaders not displaying properly

### ISSUE THREAD

**Issue by Dragmoria** [modmuss50/OptiFabric#83]
While using optifabric after a day or so the shaders change from working and displaying all colours correctly to some blocks being completely discoloured. After reïnstalling minecraft and all the mods they worked fine again. About a day later the same issue happened again.

![image](https://user-images.githubusercontent.com/57449002/68308155-a91f5800-00ac-11ea-93a1-b1ea3f878de4.png)

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
