### ISSUE TITLE
"Error loading OptiFabric" on latest Fabric-Loader version.

### ISSUE THREAD

**Issue by Freakyjoni** [modmuss50/OptiFabric#85]
When I try to start Minecraft with 
- OptiFabric,
- Optifine,
- Fabric API,
- Replaymod
i get the following error. (see attached)
![Minecraft OptiFabric #1](https://user-images.githubusercontent.com/57573798/68534682-7c32a580-0337-11ea-91b3-185cd8cd7cc2.PNG)
![Minecraft OptiFabric #2](https://user-images.githubusercontent.com/57573798/68534683-7c32a580-0337-11ea-9cd2-bb4e76404e86.PNG)

**Comment by ThePieGuyWill** [comment]
Same here! This all seems to be happening today or something because it wasn't happened a couple days ago! (I think?)

**Comment by modmuss50** [comment]
For now use an older version of fabric loader, 0.6.3 should work just fine.

![](https://ss.modmuss50.me/javaw_2019-11-09_23-39-46.png)

A lot of work is required to fix this.

**Comment by modmuss50** [comment]
@Dinolek did the work for me! 0.6.0 has been released please all update!

**Comment by nathan10nathan** [comment]
I installed an earlier version, still not working.
