### ISSUE TITLE
Failed to load OptiFabric

### ISSUE THREAD

**Issue by imflou** [modmuss50/OptiFabric#86]
When i open MC, a message appears saying: 
There was an error loading OptiFabric
Failed to load Optifine, check the log for more info
me.modmuss50.optifabric.patcher.LambadaRebuilder.load(Lnet/fabricmc/tinyremapper/IMappingProvider$MappingAcceptor;)V

https://pastebin.com/DdRuDYaM

**Comment by nathan10nathan** [comment]
Same thing is happening to me!

**Comment by locoboi** [comment]
exact same problem here

**Comment by ThePieGuyWill** [comment]
Same here! This all seems to be happening today or something because it wasn't happened a couple days ago! (I think?)

**Comment by modmuss50** [comment]
OptiFabric doesnt work with the newest version of Fabric Loader, downgrade to an older version for now untill its fixed.

This is a duplicate of #85

**Comment by modmuss50** [comment]
0.6.0 has been released, please update to fix the issue.
