### ISSUE TITLE
Dynamic Lightning & Better Grass are broken with API 175

### ISSUE THREAD

**Issue by MythikAngel** [modmuss50/OptiFabric#9]
Using the newest Fabric API build (175) on Minecraft 1.14.2, dynamic lightning is broken. It only seems to work on mobs and liquids, and not on the environment.

![Screenshot](https://i.imgur.com/obb776C.png)

Better Grass also doesn't seem to work at all on the newest API.

However, downgrading to API build 157a seems to fix both of the mentioned problems on 1.14.2.

Test specs:
```
Minecraft: 1.14.2
Fabric loader: 1.14.2+build.1-0.4.8+build.154
Fabric API: 0.3.0 build 175
Optifine: preview_OptiFine_1.14.2_HD_U_F1_pre6
OptiFabric: 0.2.0
```

**Comment by modmuss50** [comment]
Humm, I’ll need to have a look at this

**Comment by modmuss50** [comment]
Ok, had a play around. Seems to be another issue caused by the rendering api.

Also seems connected textures on the glass are not working.

**Comment by modmuss50** [comment]
This issue will not be fixed, sorry about that.

More info: https://github.com/modmuss50/OptiFabric/blob/master/README.md
