### ISSUE TITLE
Optifabric causing crash at launch

### ISSUE THREAD

**Issue by greyedgaymer** [modmuss50/OptiFabric#96]
[latest.log](https://github.com/modmuss50/OptiFabric/files/3867989/latest.log)
I can confidently say that its not any of the mods being warned about, because it runs fine without Optifabric. Should I use an older version of Optifine, or Fabric Mod Loader?

**Comment by Alessandro404** [comment]
I can add my 
[latest.log](https://github.com/modmuss50/OptiFabric/files/3868403/latest.log)

Latest Fabric (0.7.0+Build.171), Latest FabricApi (in case that matters)([1.14.4] Fabric API 0.4.1 build 245) Latest OptiFabric(optifabric-0.6.0.jar)

No crash log generated. The game run fine without your mod and this log was generated disabling all other mods for good measure.

Thank You

**Comment by ghost** [comment]
Same issue with same log messages

**Comment by PlazmaKG** [comment]
You need to use optifabric with Fabric 0.6.4.

**Comment by AdamZGamer** [comment]
yes use 0.6.4!
i had the same problem and it fixed it!

**Comment by modmuss50** [comment]
Fixed please update to this version: https://github.com/modmuss50/OptiFabric/releases/tag/0.7.0
