### ISSUE TITLE
Optifabric could not find the Optifine jar in the mods folder.

### ISSUE THREAD

**Issue by NoobieNewb** [modmuss50/OptiFabric#99]
I am running MultiMC with Fabric 0.6.4 on Minecraft 1.14.2. 
Because of the Minecraft version, I could only run a preview version of Optifine, but I can confirm that it is working properly. I used the launchwrapper tweaker way according to [MultiMC's guide](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine). However, doing this breaks Fabric and I am unable to launch any mods. According to MultiMC's page, I need to use OptiFabric.

I assume it is simply the way the OptiFabric detects Optifine's name that needs to be tweaked. 
The Optifine's installer jar is: 
>preview_OptiFine_1.14.2_HD_U_F1_pre10.jar  

Extracting this yields
>OptiFine_1.14.2_HD_U_F1_pre10_MOD.jar

Renaming the preview file to OptiFine_1.14.2_HD_U_F1_pre10.jar does not help.

Edit: I have some progress. After looking at the source code, I found the snippet of the code that outputs the error message, inside the OptifineVersion.java, in public static File findOptifineJar(),
which lead me to private static JarType getJarType(). Specifically, 
>JarEntry jarEntry = jarFile.getJarEntry("net/optifine/Config.class"); // New 1.14.3 location   

Editing the optifine jar by copying the Config.class from the root folder to the net/optifine and rezipping it as jar managed to get me to pass the error.

This however, leads me to another error, OptiFabric asks to update the Fabric API. 
Using OptiFabric (0.5.2 and 0.6.4) with Fabric API 0.4.1 gets me an error message of 
>OptiFabric: Render Regions is not supported  

and opening a world crashes the game

Using an older OptiFabric(0.2 and 0.3) with the appropriate Fabric API(0.3.0 build 185) leads to invisible blocks with only water, lava, and mobs visible

This is where I got stuck.
![2019-11-23_04 51 59](https://user-images.githubusercontent.com/29788705/69476866-42d54d80-0dad-11ea-9910-662131caf01e.png)

**Comment by modmuss50** [comment]
Fixed please update to this version: https://github.com/modmuss50/OptiFabric/releases/tag/0.7.0
